name: Build CLI

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        # Install system dependencies
        sudo apt-get update
        sudo apt-get install -y qrencode xorg-dev libx11-dev libxrandr-dev libxtst-dev

        # Install Go dependencies
        go mod download

    - name: Build CLI
      run: |
        chmod +x build-cli.sh
        ./build-cli.sh

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/phone-mouse-cli-linux-amd64
        asset_name: phone-mouse
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my latest application build"

    - name: List artifacts
      run: ls -R dist/